import numpy as np

v = np.zeros(5)
w = np.arange(0,30,2)
x = np.arange(10)
y = np.arange(-10,1)
z = np.random.randn(10)
u = np.linspace(-10,10,10)
t = np.logspace(0,10,11,base=2)
print('v={}'.format(v))
print('w={}'.format(w))
print('x={}'.format(x))
print('y={}'.format(y))
print('z={}'.format(z))
print('u={}'.format(u))
print('t={}'.format(t))
